### ISSUE TITLE
Unable to add erflux as dependency

### ISSUE THREAD

**Issue by kansi** [gossiperl/erflux#11]
When including erflux as dependency the following error occurs while compiling & releasing with rebar3

```
Errors generating release 
          erflux: Bad parameter in .app file: registered
```

Which occurs because the application is registered as `{registered, erflux_app}` instead of `{registered, [erflux_app]}` in erflux.app.src file.

**Comment by radekg** [comment]
@kansi could you please verify?

**Comment by kansi** [comment]
I verified, it works.

**Comment by radekg** [comment]
Merged and tagged. Apologies for a delay on such a simple thing. I am extremely busy at the moment.
