### ISSUE TITLE
The wrong code in README

### ISSUE THREAD

**Issue by Howld** [gossiperl/erflux#13]
The code in README
<pre>
Starting with additional configuration:

application:start(crypto),
application:start(asn1),
application:start(public_key),
application:start(ssl),
application:start(idna),
application:start(hackney),
application:start(jsx),
application:load(erflux),
application:set_env(erflux, host, <<"192.168.50.115">>),
application:set_env(erflux, port, 8086),
application:set_env(erflux, username, <<"root">>),
application:set_env(erflux, password, <<"root">>),
application:set_env(erflux, ssl, false),
application:set_env(erflux, timeout, infinity),
application:start(erflux),
erflux_sup:add_erflux(erflux_http),
erflux_http:get_databases().
</pre>

The code in erflux_sup.erl
<pre>
-spec add_erflux( Name :: atom() ) -> statup_result().
%% @doc Starts instance of erflux with a given name. If name other than erflux_http, pid() versions of erflux_http functions have to be used.
add_erflux(Name) ->
  add_erflux_internal( Name, #erflux_config{} ).
</pre>

Issue:
    When you invoke function application:set_env/3 before function erflux_sup:add_erflux/1,  erflux_config actually won't change.

**Comment by radekg** [comment]
Hey @Howld, thank you for reporting. That's embarrassing! Out of curiosity, did you manage to get that code right? Would you mind opening a pull request?

**Comment by radekg** [comment]
Fixed with https://github.com/gossiperl/erflux/pull/14.
